### ISSUE TITLE
PA Review: Status Tags

### ISSUE THREAD

**Issue by Pchao93** [Pchao93/goodPlays#5]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by dobrynin** [comment]
When I click the big "Want to Play" button beneath a game, it disappears from the "All games" collection. Is this the intended behavior?

**Comment by dobrynin** [comment]
I still don't fully understand what the big buttons under the games do. Why do they differ between games? What is clicking on the button supposed to do? Is this an intuitive system for users?

**Comment by Pchao93** [comment]
The button is pretty much lifted from goodreads itself. The big button represents the status tag as determined by which default collection it is in ("Want to Play", "Playing", "Have Played")

When the button is purple, it defaults to "Want to Play", and clicking it will give it the "Want to Play" status by adding it to the "Want to Play" default collection. 

When the button is white, the meaning is the game's current played status. I might add a check box icon of some sort to help distinguish that meaning if you think it is helpful.
