### ISSUE TITLE
PA Review: Reviews

### ISSUE THREAD

**Issue by Pchao93** [Pchao93/goodPlays#6]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by dobrynin** [comment]
It took me a while to realize that the review form would only pop up if I inputted a star rating first. Might want to always provide the form as an option.
